import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Donate Crypto | Index</title>
        <meta charSet='utf-8'/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    
      </Head>
      <div className='container px-4 py-5'>
        <div className='row flex-lg-row-reverse align-items-center py-5 g-5'>
          <div className='col-10 col-sm-8 col-lg-6'>

          </div>
        </div>
      <h1>Donate Crypto</h1>
      </div>
    </>
  )
}
